/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as UrlsRouteImport } from './routes/urls'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CanvasRouteImport } from './routes/canvas'
import { Route as BlocksRouteImport } from './routes/blocks'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as UsernameRouteImport } from './routes/$username'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CanvasIndexRouteImport } from './routes/canvas.index'
import { Route as I1focusDemoRouteImport } from './routes/i.1focus-demo'
import { Route as CanvasCanvasIdRouteImport } from './routes/canvas.$canvasId'
import { Route as ArchiveArchiveIdRouteImport } from './routes/archive.$archiveId'
import { Route as ApiUsersRouteImport } from './routes/api/users'
import { Route as ApiUsageEventsRouteImport } from './routes/api/usage-events'
import { Route as ApiStreamReplaysRouteImport } from './routes/api/stream-replays'
import { Route as ApiStreamCommentsRouteImport } from './routes/api/stream-comments'
import { Route as ApiStreamRouteImport } from './routes/api/stream'
import { Route as ApiProfileRouteImport } from './routes/api/profile'
import { Route as ApiContextItemsRouteImport } from './routes/api/context-items'
import { Route as ApiChatThreadsRouteImport } from './routes/api/chat-threads'
import { Route as ApiChatMessagesRouteImport } from './routes/api/chat-messages'
import { Route as ApiCanvasRouteImport } from './routes/api/canvas'
import { Route as ApiBrowserSessionsRouteImport } from './routes/api/browser-sessions'
import { Route as ApiArchivesRouteImport } from './routes/api/archives'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as ApiUsersUsernameRouteImport } from './routes/api/users.username'
import { Route as ApiUsageEventsCreateRouteImport } from './routes/api/usage-events.create'
import { Route as ApiStripeWebhooksRouteImport } from './routes/api/stripe/webhooks'
import { Route as ApiStripePortalRouteImport } from './routes/api/stripe/portal'
import { Route as ApiStripeCheckoutRouteImport } from './routes/api/stripe/checkout'
import { Route as ApiStripeBillingRouteImport } from './routes/api/stripe/billing'
import { Route as ApiStreamsUsernameRouteImport } from './routes/api/streams.$username'
import { Route as ApiStreamReplaysReplayIdRouteImport } from './routes/api/stream-replays.$replayId'
import { Route as ApiSpotifyNowPlayingRouteImport } from './routes/api/spotify.now-playing'
import { Route as ApiFlowgladSplatRouteImport } from './routes/api/flowglad/$'
import { Route as ApiChatMutationsRouteImport } from './routes/api/chat/mutations'
import { Route as ApiChatGuestRouteImport } from './routes/api/chat/guest'
import { Route as ApiChatAiRouteImport } from './routes/api/chat/ai'
import { Route as ApiCanvasImagesRouteImport } from './routes/api/canvas.images'
import { Route as ApiCanvasCanvasIdRouteImport } from './routes/api/canvas.$canvasId'
import { Route as ApiBrowserSessionsSessionIdRouteImport } from './routes/api/browser-sessions.$sessionId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiArchivesArchiveIdRouteImport } from './routes/api/archives.$archiveId'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'
import { Route as ApiStreamsUsernameViewersRouteImport } from './routes/api/streams.$username.viewers'
import { Route as ApiStreamsUsernameReplaysRouteImport } from './routes/api/streams.$username.replays'
import { Route as ApiCanvasImagesImageIdRouteImport } from './routes/api/canvas.images.$imageId'
import { Route as ApiCanvasImagesImageIdGenerateRouteImport } from './routes/api/canvas.images.$imageId.generate'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const UrlsRoute = UrlsRouteImport.update({
  id: '/urls',
  path: '/urls',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvasRoute = CanvasRouteImport.update({
  id: '/canvas',
  path: '/canvas',
  getParentRoute: () => rootRouteImport,
} as any)
const BlocksRoute = BlocksRouteImport.update({
  id: '/blocks',
  path: '/blocks',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernameRoute = UsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvasIndexRoute = CanvasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CanvasRoute,
} as any)
const I1focusDemoRoute = I1focusDemoRouteImport.update({
  id: '/i/1focus-demo',
  path: '/i/1focus-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvasCanvasIdRoute = CanvasCanvasIdRouteImport.update({
  id: '/$canvasId',
  path: '/$canvasId',
  getParentRoute: () => CanvasRoute,
} as any)
const ArchiveArchiveIdRoute = ArchiveArchiveIdRouteImport.update({
  id: '/$archiveId',
  path: '/$archiveId',
  getParentRoute: () => ArchiveRoute,
} as any)
const ApiUsersRoute = ApiUsersRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsageEventsRoute = ApiUsageEventsRouteImport.update({
  id: '/api/usage-events',
  path: '/api/usage-events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStreamReplaysRoute = ApiStreamReplaysRouteImport.update({
  id: '/api/stream-replays',
  path: '/api/stream-replays',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStreamCommentsRoute = ApiStreamCommentsRouteImport.update({
  id: '/api/stream-comments',
  path: '/api/stream-comments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStreamRoute = ApiStreamRouteImport.update({
  id: '/api/stream',
  path: '/api/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileRoute = ApiProfileRouteImport.update({
  id: '/api/profile',
  path: '/api/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContextItemsRoute = ApiContextItemsRouteImport.update({
  id: '/api/context-items',
  path: '/api/context-items',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatThreadsRoute = ApiChatThreadsRouteImport.update({
  id: '/api/chat-threads',
  path: '/api/chat-threads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatMessagesRoute = ApiChatMessagesRouteImport.update({
  id: '/api/chat-messages',
  path: '/api/chat-messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCanvasRoute = ApiCanvasRouteImport.update({
  id: '/api/canvas',
  path: '/api/canvas',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrowserSessionsRoute = ApiBrowserSessionsRouteImport.update({
  id: '/api/browser-sessions',
  path: '/api/browser-sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArchivesRoute = ApiArchivesRouteImport.update({
  id: '/api/archives',
  path: '/api/archives',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersUsernameRoute = ApiUsersUsernameRouteImport.update({
  id: '/username',
  path: '/username',
  getParentRoute: () => ApiUsersRoute,
} as any)
const ApiUsageEventsCreateRoute = ApiUsageEventsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => ApiUsageEventsRoute,
} as any)
const ApiStripeWebhooksRoute = ApiStripeWebhooksRouteImport.update({
  id: '/api/stripe/webhooks',
  path: '/api/stripe/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripePortalRoute = ApiStripePortalRouteImport.update({
  id: '/api/stripe/portal',
  path: '/api/stripe/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeCheckoutRoute = ApiStripeCheckoutRouteImport.update({
  id: '/api/stripe/checkout',
  path: '/api/stripe/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeBillingRoute = ApiStripeBillingRouteImport.update({
  id: '/api/stripe/billing',
  path: '/api/stripe/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStreamsUsernameRoute = ApiStreamsUsernameRouteImport.update({
  id: '/api/streams/$username',
  path: '/api/streams/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStreamReplaysReplayIdRoute =
  ApiStreamReplaysReplayIdRouteImport.update({
    id: '/$replayId',
    path: '/$replayId',
    getParentRoute: () => ApiStreamReplaysRoute,
  } as any)
const ApiSpotifyNowPlayingRoute = ApiSpotifyNowPlayingRouteImport.update({
  id: '/api/spotify/now-playing',
  path: '/api/spotify/now-playing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFlowgladSplatRoute = ApiFlowgladSplatRouteImport.update({
  id: '/api/flowglad/$',
  path: '/api/flowglad/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatMutationsRoute = ApiChatMutationsRouteImport.update({
  id: '/api/chat/mutations',
  path: '/api/chat/mutations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatGuestRoute = ApiChatGuestRouteImport.update({
  id: '/api/chat/guest',
  path: '/api/chat/guest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatAiRoute = ApiChatAiRouteImport.update({
  id: '/api/chat/ai',
  path: '/api/chat/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCanvasImagesRoute = ApiCanvasImagesRouteImport.update({
  id: '/images',
  path: '/images',
  getParentRoute: () => ApiCanvasRoute,
} as any)
const ApiCanvasCanvasIdRoute = ApiCanvasCanvasIdRouteImport.update({
  id: '/$canvasId',
  path: '/$canvasId',
  getParentRoute: () => ApiCanvasRoute,
} as any)
const ApiBrowserSessionsSessionIdRoute =
  ApiBrowserSessionsSessionIdRouteImport.update({
    id: '/$sessionId',
    path: '/$sessionId',
    getParentRoute: () => ApiBrowserSessionsRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArchivesArchiveIdRoute = ApiArchivesArchiveIdRouteImport.update({
  id: '/$archiveId',
  path: '/$archiveId',
  getParentRoute: () => ApiArchivesRoute,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStreamsUsernameViewersRoute =
  ApiStreamsUsernameViewersRouteImport.update({
    id: '/viewers',
    path: '/viewers',
    getParentRoute: () => ApiStreamsUsernameRoute,
  } as any)
const ApiStreamsUsernameReplaysRoute =
  ApiStreamsUsernameReplaysRouteImport.update({
    id: '/replays',
    path: '/replays',
    getParentRoute: () => ApiStreamsUsernameRoute,
  } as any)
const ApiCanvasImagesImageIdRoute = ApiCanvasImagesImageIdRouteImport.update({
  id: '/$imageId',
  path: '/$imageId',
  getParentRoute: () => ApiCanvasImagesRoute,
} as any)
const ApiCanvasImagesImageIdGenerateRoute =
  ApiCanvasImagesImageIdGenerateRouteImport.update({
    id: '/generate',
    path: '/generate',
    getParentRoute: () => ApiCanvasImagesImageIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$username': typeof UsernameRoute
  '/archive': typeof ArchiveRouteWithChildren
  '/auth': typeof AuthRoute
  '/blocks': typeof BlocksRoute
  '/canvas': typeof CanvasRouteWithChildren
  '/chat': typeof ChatRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/urls': typeof UrlsRoute
  '/users': typeof UsersRoute
  '/api/archives': typeof ApiArchivesRouteWithChildren
  '/api/browser-sessions': typeof ApiBrowserSessionsRouteWithChildren
  '/api/canvas': typeof ApiCanvasRouteWithChildren
  '/api/chat-messages': typeof ApiChatMessagesRoute
  '/api/chat-threads': typeof ApiChatThreadsRoute
  '/api/context-items': typeof ApiContextItemsRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/stream': typeof ApiStreamRoute
  '/api/stream-comments': typeof ApiStreamCommentsRoute
  '/api/stream-replays': typeof ApiStreamReplaysRouteWithChildren
  '/api/usage-events': typeof ApiUsageEventsRouteWithChildren
  '/api/users': typeof ApiUsersRouteWithChildren
  '/archive/$archiveId': typeof ArchiveArchiveIdRoute
  '/canvas/$canvasId': typeof CanvasCanvasIdRoute
  '/i/1focus-demo': typeof I1focusDemoRoute
  '/canvas/': typeof CanvasIndexRoute
  '/api/archives/$archiveId': typeof ApiArchivesArchiveIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/browser-sessions/$sessionId': typeof ApiBrowserSessionsSessionIdRoute
  '/api/canvas/$canvasId': typeof ApiCanvasCanvasIdRoute
  '/api/canvas/images': typeof ApiCanvasImagesRouteWithChildren
  '/api/chat/ai': typeof ApiChatAiRoute
  '/api/chat/guest': typeof ApiChatGuestRoute
  '/api/chat/mutations': typeof ApiChatMutationsRoute
  '/api/flowglad/$': typeof ApiFlowgladSplatRoute
  '/api/spotify/now-playing': typeof ApiSpotifyNowPlayingRoute
  '/api/stream-replays/$replayId': typeof ApiStreamReplaysReplayIdRoute
  '/api/streams/$username': typeof ApiStreamsUsernameRouteWithChildren
  '/api/stripe/billing': typeof ApiStripeBillingRoute
  '/api/stripe/checkout': typeof ApiStripeCheckoutRoute
  '/api/stripe/portal': typeof ApiStripePortalRoute
  '/api/stripe/webhooks': typeof ApiStripeWebhooksRoute
  '/api/usage-events/create': typeof ApiUsageEventsCreateRoute
  '/api/users/username': typeof ApiUsersUsernameRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/api/canvas/images/$imageId': typeof ApiCanvasImagesImageIdRouteWithChildren
  '/api/streams/$username/replays': typeof ApiStreamsUsernameReplaysRoute
  '/api/streams/$username/viewers': typeof ApiStreamsUsernameViewersRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
  '/api/canvas/images/$imageId/generate': typeof ApiCanvasImagesImageIdGenerateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$username': typeof UsernameRoute
  '/archive': typeof ArchiveRouteWithChildren
  '/auth': typeof AuthRoute
  '/blocks': typeof BlocksRoute
  '/chat': typeof ChatRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/urls': typeof UrlsRoute
  '/users': typeof UsersRoute
  '/api/archives': typeof ApiArchivesRouteWithChildren
  '/api/browser-sessions': typeof ApiBrowserSessionsRouteWithChildren
  '/api/canvas': typeof ApiCanvasRouteWithChildren
  '/api/chat-messages': typeof ApiChatMessagesRoute
  '/api/chat-threads': typeof ApiChatThreadsRoute
  '/api/context-items': typeof ApiContextItemsRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/stream': typeof ApiStreamRoute
  '/api/stream-comments': typeof ApiStreamCommentsRoute
  '/api/stream-replays': typeof ApiStreamReplaysRouteWithChildren
  '/api/usage-events': typeof ApiUsageEventsRouteWithChildren
  '/api/users': typeof ApiUsersRouteWithChildren
  '/archive/$archiveId': typeof ArchiveArchiveIdRoute
  '/canvas/$canvasId': typeof CanvasCanvasIdRoute
  '/i/1focus-demo': typeof I1focusDemoRoute
  '/canvas': typeof CanvasIndexRoute
  '/api/archives/$archiveId': typeof ApiArchivesArchiveIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/browser-sessions/$sessionId': typeof ApiBrowserSessionsSessionIdRoute
  '/api/canvas/$canvasId': typeof ApiCanvasCanvasIdRoute
  '/api/canvas/images': typeof ApiCanvasImagesRouteWithChildren
  '/api/chat/ai': typeof ApiChatAiRoute
  '/api/chat/guest': typeof ApiChatGuestRoute
  '/api/chat/mutations': typeof ApiChatMutationsRoute
  '/api/flowglad/$': typeof ApiFlowgladSplatRoute
  '/api/spotify/now-playing': typeof ApiSpotifyNowPlayingRoute
  '/api/stream-replays/$replayId': typeof ApiStreamReplaysReplayIdRoute
  '/api/streams/$username': typeof ApiStreamsUsernameRouteWithChildren
  '/api/stripe/billing': typeof ApiStripeBillingRoute
  '/api/stripe/checkout': typeof ApiStripeCheckoutRoute
  '/api/stripe/portal': typeof ApiStripePortalRoute
  '/api/stripe/webhooks': typeof ApiStripeWebhooksRoute
  '/api/usage-events/create': typeof ApiUsageEventsCreateRoute
  '/api/users/username': typeof ApiUsersUsernameRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/api/canvas/images/$imageId': typeof ApiCanvasImagesImageIdRouteWithChildren
  '/api/streams/$username/replays': typeof ApiStreamsUsernameReplaysRoute
  '/api/streams/$username/viewers': typeof ApiStreamsUsernameViewersRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
  '/api/canvas/images/$imageId/generate': typeof ApiCanvasImagesImageIdGenerateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$username': typeof UsernameRoute
  '/archive': typeof ArchiveRouteWithChildren
  '/auth': typeof AuthRoute
  '/blocks': typeof BlocksRoute
  '/canvas': typeof CanvasRouteWithChildren
  '/chat': typeof ChatRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/urls': typeof UrlsRoute
  '/users': typeof UsersRoute
  '/api/archives': typeof ApiArchivesRouteWithChildren
  '/api/browser-sessions': typeof ApiBrowserSessionsRouteWithChildren
  '/api/canvas': typeof ApiCanvasRouteWithChildren
  '/api/chat-messages': typeof ApiChatMessagesRoute
  '/api/chat-threads': typeof ApiChatThreadsRoute
  '/api/context-items': typeof ApiContextItemsRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/stream': typeof ApiStreamRoute
  '/api/stream-comments': typeof ApiStreamCommentsRoute
  '/api/stream-replays': typeof ApiStreamReplaysRouteWithChildren
  '/api/usage-events': typeof ApiUsageEventsRouteWithChildren
  '/api/users': typeof ApiUsersRouteWithChildren
  '/archive/$archiveId': typeof ArchiveArchiveIdRoute
  '/canvas/$canvasId': typeof CanvasCanvasIdRoute
  '/i/1focus-demo': typeof I1focusDemoRoute
  '/canvas/': typeof CanvasIndexRoute
  '/api/archives/$archiveId': typeof ApiArchivesArchiveIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/browser-sessions/$sessionId': typeof ApiBrowserSessionsSessionIdRoute
  '/api/canvas/$canvasId': typeof ApiCanvasCanvasIdRoute
  '/api/canvas/images': typeof ApiCanvasImagesRouteWithChildren
  '/api/chat/ai': typeof ApiChatAiRoute
  '/api/chat/guest': typeof ApiChatGuestRoute
  '/api/chat/mutations': typeof ApiChatMutationsRoute
  '/api/flowglad/$': typeof ApiFlowgladSplatRoute
  '/api/spotify/now-playing': typeof ApiSpotifyNowPlayingRoute
  '/api/stream-replays/$replayId': typeof ApiStreamReplaysReplayIdRoute
  '/api/streams/$username': typeof ApiStreamsUsernameRouteWithChildren
  '/api/stripe/billing': typeof ApiStripeBillingRoute
  '/api/stripe/checkout': typeof ApiStripeCheckoutRoute
  '/api/stripe/portal': typeof ApiStripePortalRoute
  '/api/stripe/webhooks': typeof ApiStripeWebhooksRoute
  '/api/usage-events/create': typeof ApiUsageEventsCreateRoute
  '/api/users/username': typeof ApiUsersUsernameRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/api/canvas/images/$imageId': typeof ApiCanvasImagesImageIdRouteWithChildren
  '/api/streams/$username/replays': typeof ApiStreamsUsernameReplaysRoute
  '/api/streams/$username/viewers': typeof ApiStreamsUsernameViewersRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
  '/api/canvas/images/$imageId/generate': typeof ApiCanvasImagesImageIdGenerateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$username'
    | '/archive'
    | '/auth'
    | '/blocks'
    | '/canvas'
    | '/chat'
    | '/login'
    | '/marketplace'
    | '/sessions'
    | '/settings'
    | '/urls'
    | '/users'
    | '/api/archives'
    | '/api/browser-sessions'
    | '/api/canvas'
    | '/api/chat-messages'
    | '/api/chat-threads'
    | '/api/context-items'
    | '/api/profile'
    | '/api/stream'
    | '/api/stream-comments'
    | '/api/stream-replays'
    | '/api/usage-events'
    | '/api/users'
    | '/archive/$archiveId'
    | '/canvas/$canvasId'
    | '/i/1focus-demo'
    | '/canvas/'
    | '/api/archives/$archiveId'
    | '/api/auth/$'
    | '/api/browser-sessions/$sessionId'
    | '/api/canvas/$canvasId'
    | '/api/canvas/images'
    | '/api/chat/ai'
    | '/api/chat/guest'
    | '/api/chat/mutations'
    | '/api/flowglad/$'
    | '/api/spotify/now-playing'
    | '/api/stream-replays/$replayId'
    | '/api/streams/$username'
    | '/api/stripe/billing'
    | '/api/stripe/checkout'
    | '/api/stripe/portal'
    | '/api/stripe/webhooks'
    | '/api/usage-events/create'
    | '/api/users/username'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/api/canvas/images/$imageId'
    | '/api/streams/$username/replays'
    | '/api/streams/$username/viewers'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
    | '/api/canvas/images/$imageId/generate'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$username'
    | '/archive'
    | '/auth'
    | '/blocks'
    | '/chat'
    | '/login'
    | '/marketplace'
    | '/sessions'
    | '/settings'
    | '/urls'
    | '/users'
    | '/api/archives'
    | '/api/browser-sessions'
    | '/api/canvas'
    | '/api/chat-messages'
    | '/api/chat-threads'
    | '/api/context-items'
    | '/api/profile'
    | '/api/stream'
    | '/api/stream-comments'
    | '/api/stream-replays'
    | '/api/usage-events'
    | '/api/users'
    | '/archive/$archiveId'
    | '/canvas/$canvasId'
    | '/i/1focus-demo'
    | '/canvas'
    | '/api/archives/$archiveId'
    | '/api/auth/$'
    | '/api/browser-sessions/$sessionId'
    | '/api/canvas/$canvasId'
    | '/api/canvas/images'
    | '/api/chat/ai'
    | '/api/chat/guest'
    | '/api/chat/mutations'
    | '/api/flowglad/$'
    | '/api/spotify/now-playing'
    | '/api/stream-replays/$replayId'
    | '/api/streams/$username'
    | '/api/stripe/billing'
    | '/api/stripe/checkout'
    | '/api/stripe/portal'
    | '/api/stripe/webhooks'
    | '/api/usage-events/create'
    | '/api/users/username'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/api/canvas/images/$imageId'
    | '/api/streams/$username/replays'
    | '/api/streams/$username/viewers'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
    | '/api/canvas/images/$imageId/generate'
  id:
    | '__root__'
    | '/'
    | '/$username'
    | '/archive'
    | '/auth'
    | '/blocks'
    | '/canvas'
    | '/chat'
    | '/login'
    | '/marketplace'
    | '/sessions'
    | '/settings'
    | '/urls'
    | '/users'
    | '/api/archives'
    | '/api/browser-sessions'
    | '/api/canvas'
    | '/api/chat-messages'
    | '/api/chat-threads'
    | '/api/context-items'
    | '/api/profile'
    | '/api/stream'
    | '/api/stream-comments'
    | '/api/stream-replays'
    | '/api/usage-events'
    | '/api/users'
    | '/archive/$archiveId'
    | '/canvas/$canvasId'
    | '/i/1focus-demo'
    | '/canvas/'
    | '/api/archives/$archiveId'
    | '/api/auth/$'
    | '/api/browser-sessions/$sessionId'
    | '/api/canvas/$canvasId'
    | '/api/canvas/images'
    | '/api/chat/ai'
    | '/api/chat/guest'
    | '/api/chat/mutations'
    | '/api/flowglad/$'
    | '/api/spotify/now-playing'
    | '/api/stream-replays/$replayId'
    | '/api/streams/$username'
    | '/api/stripe/billing'
    | '/api/stripe/checkout'
    | '/api/stripe/portal'
    | '/api/stripe/webhooks'
    | '/api/usage-events/create'
    | '/api/users/username'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/api/canvas/images/$imageId'
    | '/api/streams/$username/replays'
    | '/api/streams/$username/viewers'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
    | '/api/canvas/images/$imageId/generate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UsernameRoute: typeof UsernameRoute
  ArchiveRoute: typeof ArchiveRouteWithChildren
  AuthRoute: typeof AuthRoute
  BlocksRoute: typeof BlocksRoute
  CanvasRoute: typeof CanvasRouteWithChildren
  ChatRoute: typeof ChatRoute
  LoginRoute: typeof LoginRoute
  MarketplaceRoute: typeof MarketplaceRoute
  SessionsRoute: typeof SessionsRoute
  SettingsRoute: typeof SettingsRoute
  UrlsRoute: typeof UrlsRoute
  UsersRoute: typeof UsersRoute
  ApiArchivesRoute: typeof ApiArchivesRouteWithChildren
  ApiBrowserSessionsRoute: typeof ApiBrowserSessionsRouteWithChildren
  ApiCanvasRoute: typeof ApiCanvasRouteWithChildren
  ApiChatMessagesRoute: typeof ApiChatMessagesRoute
  ApiChatThreadsRoute: typeof ApiChatThreadsRoute
  ApiContextItemsRoute: typeof ApiContextItemsRoute
  ApiProfileRoute: typeof ApiProfileRoute
  ApiStreamRoute: typeof ApiStreamRoute
  ApiStreamCommentsRoute: typeof ApiStreamCommentsRoute
  ApiStreamReplaysRoute: typeof ApiStreamReplaysRouteWithChildren
  ApiUsageEventsRoute: typeof ApiUsageEventsRouteWithChildren
  ApiUsersRoute: typeof ApiUsersRouteWithChildren
  I1focusDemoRoute: typeof I1focusDemoRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiChatAiRoute: typeof ApiChatAiRoute
  ApiChatGuestRoute: typeof ApiChatGuestRoute
  ApiChatMutationsRoute: typeof ApiChatMutationsRoute
  ApiFlowgladSplatRoute: typeof ApiFlowgladSplatRoute
  ApiSpotifyNowPlayingRoute: typeof ApiSpotifyNowPlayingRoute
  ApiStreamsUsernameRoute: typeof ApiStreamsUsernameRouteWithChildren
  ApiStripeBillingRoute: typeof ApiStripeBillingRoute
  ApiStripeCheckoutRoute: typeof ApiStripeCheckoutRoute
  ApiStripePortalRoute: typeof ApiStripePortalRoute
  ApiStripeWebhooksRoute: typeof ApiStripeWebhooksRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/urls': {
      id: '/urls'
      path: '/urls'
      fullPath: '/urls'
      preLoaderRoute: typeof UrlsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canvas': {
      id: '/canvas'
      path: '/canvas'
      fullPath: '/canvas'
      preLoaderRoute: typeof CanvasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocks': {
      id: '/blocks'
      path: '/blocks'
      fullPath: '/blocks'
      preLoaderRoute: typeof BlocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username': {
      id: '/$username'
      path: '/$username'
      fullPath: '/$username'
      preLoaderRoute: typeof UsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canvas/': {
      id: '/canvas/'
      path: '/'
      fullPath: '/canvas/'
      preLoaderRoute: typeof CanvasIndexRouteImport
      parentRoute: typeof CanvasRoute
    }
    '/i/1focus-demo': {
      id: '/i/1focus-demo'
      path: '/i/1focus-demo'
      fullPath: '/i/1focus-demo'
      preLoaderRoute: typeof I1focusDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canvas/$canvasId': {
      id: '/canvas/$canvasId'
      path: '/$canvasId'
      fullPath: '/canvas/$canvasId'
      preLoaderRoute: typeof CanvasCanvasIdRouteImport
      parentRoute: typeof CanvasRoute
    }
    '/archive/$archiveId': {
      id: '/archive/$archiveId'
      path: '/$archiveId'
      fullPath: '/archive/$archiveId'
      preLoaderRoute: typeof ArchiveArchiveIdRouteImport
      parentRoute: typeof ArchiveRoute
    }
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/usage-events': {
      id: '/api/usage-events'
      path: '/api/usage-events'
      fullPath: '/api/usage-events'
      preLoaderRoute: typeof ApiUsageEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stream-replays': {
      id: '/api/stream-replays'
      path: '/api/stream-replays'
      fullPath: '/api/stream-replays'
      preLoaderRoute: typeof ApiStreamReplaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stream-comments': {
      id: '/api/stream-comments'
      path: '/api/stream-comments'
      fullPath: '/api/stream-comments'
      preLoaderRoute: typeof ApiStreamCommentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stream': {
      id: '/api/stream'
      path: '/api/stream'
      fullPath: '/api/stream'
      preLoaderRoute: typeof ApiStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile': {
      id: '/api/profile'
      path: '/api/profile'
      fullPath: '/api/profile'
      preLoaderRoute: typeof ApiProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/context-items': {
      id: '/api/context-items'
      path: '/api/context-items'
      fullPath: '/api/context-items'
      preLoaderRoute: typeof ApiContextItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat-threads': {
      id: '/api/chat-threads'
      path: '/api/chat-threads'
      fullPath: '/api/chat-threads'
      preLoaderRoute: typeof ApiChatThreadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat-messages': {
      id: '/api/chat-messages'
      path: '/api/chat-messages'
      fullPath: '/api/chat-messages'
      preLoaderRoute: typeof ApiChatMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/canvas': {
      id: '/api/canvas'
      path: '/api/canvas'
      fullPath: '/api/canvas'
      preLoaderRoute: typeof ApiCanvasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/browser-sessions': {
      id: '/api/browser-sessions'
      path: '/api/browser-sessions'
      fullPath: '/api/browser-sessions'
      preLoaderRoute: typeof ApiBrowserSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/archives': {
      id: '/api/archives'
      path: '/api/archives'
      fullPath: '/api/archives'
      preLoaderRoute: typeof ApiArchivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/username': {
      id: '/api/users/username'
      path: '/username'
      fullPath: '/api/users/username'
      preLoaderRoute: typeof ApiUsersUsernameRouteImport
      parentRoute: typeof ApiUsersRoute
    }
    '/api/usage-events/create': {
      id: '/api/usage-events/create'
      path: '/create'
      fullPath: '/api/usage-events/create'
      preLoaderRoute: typeof ApiUsageEventsCreateRouteImport
      parentRoute: typeof ApiUsageEventsRoute
    }
    '/api/stripe/webhooks': {
      id: '/api/stripe/webhooks'
      path: '/api/stripe/webhooks'
      fullPath: '/api/stripe/webhooks'
      preLoaderRoute: typeof ApiStripeWebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/portal': {
      id: '/api/stripe/portal'
      path: '/api/stripe/portal'
      fullPath: '/api/stripe/portal'
      preLoaderRoute: typeof ApiStripePortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/checkout': {
      id: '/api/stripe/checkout'
      path: '/api/stripe/checkout'
      fullPath: '/api/stripe/checkout'
      preLoaderRoute: typeof ApiStripeCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/billing': {
      id: '/api/stripe/billing'
      path: '/api/stripe/billing'
      fullPath: '/api/stripe/billing'
      preLoaderRoute: typeof ApiStripeBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/streams/$username': {
      id: '/api/streams/$username'
      path: '/api/streams/$username'
      fullPath: '/api/streams/$username'
      preLoaderRoute: typeof ApiStreamsUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stream-replays/$replayId': {
      id: '/api/stream-replays/$replayId'
      path: '/$replayId'
      fullPath: '/api/stream-replays/$replayId'
      preLoaderRoute: typeof ApiStreamReplaysReplayIdRouteImport
      parentRoute: typeof ApiStreamReplaysRoute
    }
    '/api/spotify/now-playing': {
      id: '/api/spotify/now-playing'
      path: '/api/spotify/now-playing'
      fullPath: '/api/spotify/now-playing'
      preLoaderRoute: typeof ApiSpotifyNowPlayingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/flowglad/$': {
      id: '/api/flowglad/$'
      path: '/api/flowglad/$'
      fullPath: '/api/flowglad/$'
      preLoaderRoute: typeof ApiFlowgladSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/mutations': {
      id: '/api/chat/mutations'
      path: '/api/chat/mutations'
      fullPath: '/api/chat/mutations'
      preLoaderRoute: typeof ApiChatMutationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/guest': {
      id: '/api/chat/guest'
      path: '/api/chat/guest'
      fullPath: '/api/chat/guest'
      preLoaderRoute: typeof ApiChatGuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/ai': {
      id: '/api/chat/ai'
      path: '/api/chat/ai'
      fullPath: '/api/chat/ai'
      preLoaderRoute: typeof ApiChatAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/canvas/images': {
      id: '/api/canvas/images'
      path: '/images'
      fullPath: '/api/canvas/images'
      preLoaderRoute: typeof ApiCanvasImagesRouteImport
      parentRoute: typeof ApiCanvasRoute
    }
    '/api/canvas/$canvasId': {
      id: '/api/canvas/$canvasId'
      path: '/$canvasId'
      fullPath: '/api/canvas/$canvasId'
      preLoaderRoute: typeof ApiCanvasCanvasIdRouteImport
      parentRoute: typeof ApiCanvasRoute
    }
    '/api/browser-sessions/$sessionId': {
      id: '/api/browser-sessions/$sessionId'
      path: '/$sessionId'
      fullPath: '/api/browser-sessions/$sessionId'
      preLoaderRoute: typeof ApiBrowserSessionsSessionIdRouteImport
      parentRoute: typeof ApiBrowserSessionsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/archives/$archiveId': {
      id: '/api/archives/$archiveId'
      path: '/$archiveId'
      fullPath: '/api/archives/$archiveId'
      preLoaderRoute: typeof ApiArchivesArchiveIdRouteImport
      parentRoute: typeof ApiArchivesRoute
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/streams/$username/viewers': {
      id: '/api/streams/$username/viewers'
      path: '/viewers'
      fullPath: '/api/streams/$username/viewers'
      preLoaderRoute: typeof ApiStreamsUsernameViewersRouteImport
      parentRoute: typeof ApiStreamsUsernameRoute
    }
    '/api/streams/$username/replays': {
      id: '/api/streams/$username/replays'
      path: '/replays'
      fullPath: '/api/streams/$username/replays'
      preLoaderRoute: typeof ApiStreamsUsernameReplaysRouteImport
      parentRoute: typeof ApiStreamsUsernameRoute
    }
    '/api/canvas/images/$imageId': {
      id: '/api/canvas/images/$imageId'
      path: '/$imageId'
      fullPath: '/api/canvas/images/$imageId'
      preLoaderRoute: typeof ApiCanvasImagesImageIdRouteImport
      parentRoute: typeof ApiCanvasImagesRoute
    }
    '/api/canvas/images/$imageId/generate': {
      id: '/api/canvas/images/$imageId/generate'
      path: '/generate'
      fullPath: '/api/canvas/images/$imageId/generate'
      preLoaderRoute: typeof ApiCanvasImagesImageIdGenerateRouteImport
      parentRoute: typeof ApiCanvasImagesImageIdRoute
    }
  }
}

interface ArchiveRouteChildren {
  ArchiveArchiveIdRoute: typeof ArchiveArchiveIdRoute
}

const ArchiveRouteChildren: ArchiveRouteChildren = {
  ArchiveArchiveIdRoute: ArchiveArchiveIdRoute,
}

const ArchiveRouteWithChildren =
  ArchiveRoute._addFileChildren(ArchiveRouteChildren)

interface CanvasRouteChildren {
  CanvasCanvasIdRoute: typeof CanvasCanvasIdRoute
  CanvasIndexRoute: typeof CanvasIndexRoute
}

const CanvasRouteChildren: CanvasRouteChildren = {
  CanvasCanvasIdRoute: CanvasCanvasIdRoute,
  CanvasIndexRoute: CanvasIndexRoute,
}

const CanvasRouteWithChildren =
  CanvasRoute._addFileChildren(CanvasRouteChildren)

interface ApiArchivesRouteChildren {
  ApiArchivesArchiveIdRoute: typeof ApiArchivesArchiveIdRoute
}

const ApiArchivesRouteChildren: ApiArchivesRouteChildren = {
  ApiArchivesArchiveIdRoute: ApiArchivesArchiveIdRoute,
}

const ApiArchivesRouteWithChildren = ApiArchivesRoute._addFileChildren(
  ApiArchivesRouteChildren,
)

interface ApiBrowserSessionsRouteChildren {
  ApiBrowserSessionsSessionIdRoute: typeof ApiBrowserSessionsSessionIdRoute
}

const ApiBrowserSessionsRouteChildren: ApiBrowserSessionsRouteChildren = {
  ApiBrowserSessionsSessionIdRoute: ApiBrowserSessionsSessionIdRoute,
}

const ApiBrowserSessionsRouteWithChildren =
  ApiBrowserSessionsRoute._addFileChildren(ApiBrowserSessionsRouteChildren)

interface ApiCanvasImagesImageIdRouteChildren {
  ApiCanvasImagesImageIdGenerateRoute: typeof ApiCanvasImagesImageIdGenerateRoute
}

const ApiCanvasImagesImageIdRouteChildren: ApiCanvasImagesImageIdRouteChildren =
  {
    ApiCanvasImagesImageIdGenerateRoute: ApiCanvasImagesImageIdGenerateRoute,
  }

const ApiCanvasImagesImageIdRouteWithChildren =
  ApiCanvasImagesImageIdRoute._addFileChildren(
    ApiCanvasImagesImageIdRouteChildren,
  )

interface ApiCanvasImagesRouteChildren {
  ApiCanvasImagesImageIdRoute: typeof ApiCanvasImagesImageIdRouteWithChildren
}

const ApiCanvasImagesRouteChildren: ApiCanvasImagesRouteChildren = {
  ApiCanvasImagesImageIdRoute: ApiCanvasImagesImageIdRouteWithChildren,
}

const ApiCanvasImagesRouteWithChildren = ApiCanvasImagesRoute._addFileChildren(
  ApiCanvasImagesRouteChildren,
)

interface ApiCanvasRouteChildren {
  ApiCanvasCanvasIdRoute: typeof ApiCanvasCanvasIdRoute
  ApiCanvasImagesRoute: typeof ApiCanvasImagesRouteWithChildren
}

const ApiCanvasRouteChildren: ApiCanvasRouteChildren = {
  ApiCanvasCanvasIdRoute: ApiCanvasCanvasIdRoute,
  ApiCanvasImagesRoute: ApiCanvasImagesRouteWithChildren,
}

const ApiCanvasRouteWithChildren = ApiCanvasRoute._addFileChildren(
  ApiCanvasRouteChildren,
)

interface ApiStreamReplaysRouteChildren {
  ApiStreamReplaysReplayIdRoute: typeof ApiStreamReplaysReplayIdRoute
}

const ApiStreamReplaysRouteChildren: ApiStreamReplaysRouteChildren = {
  ApiStreamReplaysReplayIdRoute: ApiStreamReplaysReplayIdRoute,
}

const ApiStreamReplaysRouteWithChildren =
  ApiStreamReplaysRoute._addFileChildren(ApiStreamReplaysRouteChildren)

interface ApiUsageEventsRouteChildren {
  ApiUsageEventsCreateRoute: typeof ApiUsageEventsCreateRoute
}

const ApiUsageEventsRouteChildren: ApiUsageEventsRouteChildren = {
  ApiUsageEventsCreateRoute: ApiUsageEventsCreateRoute,
}

const ApiUsageEventsRouteWithChildren = ApiUsageEventsRoute._addFileChildren(
  ApiUsageEventsRouteChildren,
)

interface ApiUsersRouteChildren {
  ApiUsersUsernameRoute: typeof ApiUsersUsernameRoute
}

const ApiUsersRouteChildren: ApiUsersRouteChildren = {
  ApiUsersUsernameRoute: ApiUsersUsernameRoute,
}

const ApiUsersRouteWithChildren = ApiUsersRoute._addFileChildren(
  ApiUsersRouteChildren,
)

interface ApiStreamsUsernameRouteChildren {
  ApiStreamsUsernameReplaysRoute: typeof ApiStreamsUsernameReplaysRoute
  ApiStreamsUsernameViewersRoute: typeof ApiStreamsUsernameViewersRoute
}

const ApiStreamsUsernameRouteChildren: ApiStreamsUsernameRouteChildren = {
  ApiStreamsUsernameReplaysRoute: ApiStreamsUsernameReplaysRoute,
  ApiStreamsUsernameViewersRoute: ApiStreamsUsernameViewersRoute,
}

const ApiStreamsUsernameRouteWithChildren =
  ApiStreamsUsernameRoute._addFileChildren(ApiStreamsUsernameRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UsernameRoute: UsernameRoute,
  ArchiveRoute: ArchiveRouteWithChildren,
  AuthRoute: AuthRoute,
  BlocksRoute: BlocksRoute,
  CanvasRoute: CanvasRouteWithChildren,
  ChatRoute: ChatRoute,
  LoginRoute: LoginRoute,
  MarketplaceRoute: MarketplaceRoute,
  SessionsRoute: SessionsRoute,
  SettingsRoute: SettingsRoute,
  UrlsRoute: UrlsRoute,
  UsersRoute: UsersRoute,
  ApiArchivesRoute: ApiArchivesRouteWithChildren,
  ApiBrowserSessionsRoute: ApiBrowserSessionsRouteWithChildren,
  ApiCanvasRoute: ApiCanvasRouteWithChildren,
  ApiChatMessagesRoute: ApiChatMessagesRoute,
  ApiChatThreadsRoute: ApiChatThreadsRoute,
  ApiContextItemsRoute: ApiContextItemsRoute,
  ApiProfileRoute: ApiProfileRoute,
  ApiStreamRoute: ApiStreamRoute,
  ApiStreamCommentsRoute: ApiStreamCommentsRoute,
  ApiStreamReplaysRoute: ApiStreamReplaysRouteWithChildren,
  ApiUsageEventsRoute: ApiUsageEventsRouteWithChildren,
  ApiUsersRoute: ApiUsersRouteWithChildren,
  I1focusDemoRoute: I1focusDemoRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiChatAiRoute: ApiChatAiRoute,
  ApiChatGuestRoute: ApiChatGuestRoute,
  ApiChatMutationsRoute: ApiChatMutationsRoute,
  ApiFlowgladSplatRoute: ApiFlowgladSplatRoute,
  ApiSpotifyNowPlayingRoute: ApiSpotifyNowPlayingRoute,
  ApiStreamsUsernameRoute: ApiStreamsUsernameRouteWithChildren,
  ApiStripeBillingRoute: ApiStripeBillingRoute,
  ApiStripeCheckoutRoute: ApiStripeCheckoutRoute,
  ApiStripePortalRoute: ApiStripePortalRoute,
  ApiStripeWebhooksRoute: ApiStripeWebhooksRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
